name: CI
on:
  # When added to a merge queue.
  # See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
  push:
    branches:
      - test-vagrant
      - main

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  integration-vagrant:
    name: Vagrant integration
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        box:
          - rockylinux/8@9.0.0
    env:
      BOX: ${{ matrix.box }}

    steps:
      - name: Show the host info
        run: |
          set -x
          uname -a
          cat /etc/os-release
          cat /proc/cpuinfo
          free -mt
      - uses: actions/checkout@v4
#      - uses: actions/cache@v4
#        with:
#          path: /root/.vagrant.d
#          key: vagrant-${{ matrix.box }}
      - name: Set up vagrant
        run: |
          # Canonical's Vagrant 2.2.19 dpkg cannot download Fedora 38 image: https://bugs.launchpad.net/vagrant/+bug/2017828
          # So we have to install Vagrant >= 2.3.1 from the upstream: https://github.com/opencontainers/runc/blob/v1.1.8/.cirrus.yml#L41-L49
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          # Ubuntu 24 has a new config file location with a new file format layout
          #sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update
          sudo apt-get install -y libvirt-daemon libvirt-daemon-system vagrant
          sudo systemctl enable --now libvirtd
          #sudo apt-get build-dep -y vagrant ruby-libvirt
          sudo apt-get install -y --no-install-recommends libxslt-dev libxml2-dev libvirt-dev ruby-bundler ruby-dev zlib1g-dev
          sudo vagrant plugin install vagrant-libvirt
      - name: Boot VM
        run: sudo BOX=$BOX vagrant up --no-tty
      - name: test-integration
        run: sudo BOX=$BOX vagrant up --provision-with=selinux,install-runc,install-gotestsum,test-integration
      - name: test-cri-integration
        run: sudo BOX=$BOX vagrant up --provision-with=selinux,install-runc,install-gotestsum,test-cri-integration
      - name: test-cri
        run: sudo BOX=$BOX vagrant up --provision-with=selinux,install-runc,install-gotestsum,test-cri
