name: CI
on:
  push:
    branches: ['main', 'release/**', 'test-go-versions']

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  binaries:
    name: Binaries
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-22.04, actuated-arm64-4cpu-16gb, macos-12, windows-2019, windows-2022]
        go-version: ["1.21.9", "1.22.2"]
        exclude:
          - os: ${{ github.repository != 'containerd/containerd' && 'actuated-arm64-4cpu-16gb' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-go
        with:
          go-version: ${{ matrix.go-version }}
      - name: Make
        run: |
          make build
          make binaries
          go version bin/containerd
